name: "Home Assistant Anywhere"
description: "Access your Home Assistant from anywhere via homeassistantanywhere.com"
version: "1.0.1"
slug: "haa"
url: "https://homeassistantanywhere.com"
image: ghcr.io/homeassistantanywhere/haa-addon-{arch}
arch:
  - amd64
  - aarch64
  - armv7
init: false
homeassistant_api: true
map:
  - homeassistant_config:ro
options:
  connection_key: ""
schema:
  connection_key: "match(^[a-zA-Z0-9_-]{3,}$)"
